name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale Linter
      uses: errata-ai/vale-action@v1.0.1
      with:
        files: doc/
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
