name: CI
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Vale Linter
      uses: errata-ai/vale-action@v1.0.1
      with:
        config: https://raw.githubusercontent.com/jessica-mitchell/test_the_docs/master/.vale.ini
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
